FROM node:17-alpine AS base



FROM base as builder

WORKDIR /app

COPY packages/bot ./packages/bot
COPY packages/db ./packages/db
COPY packages/services ./packages/services

RUN npm install

RUN npm generate

RUN npx tsc

FROM base

WORKDIR /app

COPY --from=builder /app/package*.json .
COPY --from=builder /app/packages/db ./packages/db
COPY --from=builder /app/packages/services ./packages/services



RUN npm ci --omit=dev

EXPOSE 8000

CMD ["node", "app.js"]